"""initial migration

Revision ID: d4d60fdd50f3
Revises: 
Create Date: 2018-06-30 16:49:18.519507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d60fdd50f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_usersbyday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_code', sa.String(length=10), nullable=True),
    sa.Column('hight_price', sa.String(length=10), nullable=True),
    sa.Column('low_price', sa.String(length=10), nullable=True),
    sa.Column('today_startprice', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hold_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('pay_code', sa.String(length=10), nullable=True),
    sa.Column('pay_count', sa.String(length=20), nullable=True),
    sa.Column('hold_count', sa.String(length=20), nullable=True),
    sa.Column('can_pay', sa.String(length=20), nullable=True),
    sa.Column('present_price', sa.String(length=20), nullable=True),
    sa.Column('cost_price', sa.String(length=20), nullable=True),
    sa.Column('loss_price', sa.String(length=20), nullable=True),
    sa.Column('hold_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('balance', sa.String(length=20), nullable=True),
    sa.Column('members_name', sa.String(length=20), nullable=True),
    sa.Column('image_name', sa.String(length=30), nullable=True),
    sa.Column('id_card', sa.String(length=30), nullable=True),
    sa.Column('true_name', sa.String(length=60), nullable=True),
    sa.Column('pay_password', sa.String(length=20), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('own_baseuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('pay_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pay_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('history_paycode', sa.String(length=10), nullable=True),
    sa.Column('history_paymoney', sa.String(length=20), nullable=True),
    sa.Column('history_paycount', sa.String(length=20), nullable=True),
    sa.Column('history_profitloss', sa.String(length=20), nullable=True),
    sa.Column('history_paytime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pay_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('pay_type', sa.String(length=20), nullable=True),
    sa.Column('pay_code', sa.String(length=10), nullable=True),
    sa.Column('pay_price', sa.String(length=20), nullable=True),
    sa.Column('pay_count', sa.String(length=20), nullable=True),
    sa.Column('success_paycount', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('reduce_price', sa.String(length=20), nullable=True),
    sa.Column('add_price', sa.String(length=20), nullable=True),
    sa.Column('transaction_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_code', sa.String(length=10), nullable=True),
    sa.Column('pay_name', sa.String(length=20), nullable=True),
    sa.Column('transaction_time', sa.String(length=10), nullable=True),
    sa.Column('total_price', sa.String(length=20), nullable=True),
    sa.Column('image_name', sa.String(length=30), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_paybyday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_code', sa.String(length=10), nullable=True),
    sa.Column('now_price', sa.String(length=10), nullable=True),
    sa.Column('ups_downsprice', sa.String(length=10), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_paybyminute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_code', sa.String(length=10), nullable=True),
    sa.Column('now_price', sa.String(length=10), nullable=True),
    sa.Column('ups_downsprice', sa.String(length=10), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_paybyminute')
    op.drop_table('users_paybyday')
    op.drop_table('users_information')
    op.drop_table('transaction_detail')
    op.drop_table('pay_orders')
    op.drop_table('pay_detail')
    op.drop_table('own_baseuser')
    op.drop_table('members_information')
    op.drop_table('hold_information')
    op.drop_table('base_usersbyday')
    # ### end Alembic commands ###
